# isa: rv64imafdc
abi: lp64
arch: rv64imafd
gcc:
  command: riscv64-unknown-elf-gcc
  args: -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -std=gnu99 -O2
  include: common
  asm_dir: asm 
linker:
  ld: ld
  args: -static -nostdlib -nostartfiles -lm -lgcc -T
  crt: common/crt.S 
spike:
  command: 'spike -c'
objdump:
  command: riscv64-unknown-elf-objdump
  args: -D 
elf2hex:
  command: elf2hex
  args: [8, 4194304, 2147483648]
  out_file: code.mem
sim:
  command: chromite_core
  path: /home/silipwn/tools/chromite/bin/
  args: +rtldump
# extras_1:
#   command: 'ln -sf /home/rise/lavanya/gitlab/incore/chromite/bin/chromite_core .'
# extras_2:
#   command: 'ln -sf /home/rise/lavanya/gitlab/incore/chromite/bin/boot.mem .'
# extras_3:
#   command: head -n -4 rtl.dump
#   out_file: temp.dump
# extras_4:
#   command: mv temp.dump rtl.dump
# order:
#   - 'gcc'
#   - 'spike'
#   - 'disass'
#   - 'elf2hex'
#   - 'extras_1'
#   - 'extras_2'
#   - 'sim'
#   - 'extras_3'
#   - 'extras_4'
