# Generator bin path
gen_binary_path: testfloat_gen
# Instructions to generate
# Instruction and then dest, reg1, reg2, mode 
# Possible modes include:
# RNE Round to nearest, ties to Even -> 0
# RTZ Rount to Zero -> 1
# RDN Round Down -> 2
# RUP Round Up -> 3
# RMM Round to Nearest, ties to Max Magnitude -> 4
#
set_1:
    inst: [fadd.s, fsub.s, fmul.s, fdiv.s, fsqrt.s] 
    dest: 0,31
    reg1: 0,31
    reg2: 0,31
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    # Needs to be above 46464
    tests_per_instruction: 46464
    num_tests: 1
set_2:
    inst: [fadd.d, fsub.d, fmul.d, fdiv.d, fsqrt.d] 
    dest: 0,31
    reg1: 0,31
    reg2: 0,31
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    # Needs to be above 46464
    tests_per_instruction: 50000
    num_tests: 1 
set_3:
    inst: [feq.s, flt.s, fle.s, feq.d, flt.d, fle.d]
    dest: 5,9
    reg1: 0,12
    reg2: 0,10
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    tests_per_instruction: 50000
    num_tests: 1

set_4:
    inst: [fcvt.w.s, fcvt.wu.s, fcvt.s.w, fcvt.s.wu,]
    dest: 5,9
    reg1: 5,12
    reg2: 5,10
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    tests_per_instruction: 50000
    num_tests: 1

set_5:
    inst: [fcvt.l.s, fcvt.lu.s, fcvt.s.l, fcvt.s.lu ]
    dest: 5,9
    reg1: 5,12
    reg2: 5,10
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    tests_per_instruction: 50000
    num_tests: 1

set_6:
    inst: [fcvt.w.d, fcvt.wu.d, fcvt.d.w, fcvt.d.wu,]
    dest: 5,9
    reg1: 5,12
    reg2: 5,10
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    tests_per_instruction: 50000
    num_tests: 1

set_7:
    inst: [fcvt.l.d, fcvt.lu.d, fcvt.d.l, fcvt.d.lu ]
    dest: 5,9
    reg1: 5,12
    reg2: 5,10
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    tests_per_instruction: 50000
    num_tests: 1

set_8:
    inst: [fcvt.s.d, fcvt.d.s]
    dest: 5,9
    reg1: 5,12
    reg2: 5,10
    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
    tests_per_instruction: 50000
    num_tests: 1

#set_9:
#     inst: [fmadd.s, fmsub.s, fnmadd.s fnmsub.s]
#     dest: 0,9
#     reg1: 0,12
#     reg2: 0,10
#     reg3: 0,10
#     rounding-mode: [RNE]
#     tests_per_instruction: 6133248
#     num_tests: 1
#set_10:
#     inst: [fmadd.d, fmsub.d, fnmadd.d fnmsub.d]
#     dest: 0,9
#     reg1: 0,12
#     reg2: 0,10
#     reg3: 0,10
#     rounding-mode: [RNE]
#     tests_per_instruction: 6133248
#     num_tests: 1
