# Generator bin path
gen_binary_path: /home/vagrant/tools/float/TestFloat-3e/build/Linux-x86_64-GCC/testfloat_gen
# Instructions to generate
# Instruction and then dest, reg1, reg2, mode 
# Possible modes include:
# RNE Round to nearest, ties to Even -> 0
# RTZ Rount to Zero -> 1
# RDN Round Down -> 2
# RUP Round Up -> 3
# RMM Round to Nearest, ties to Max Magnitude -> 4
#
#set_1:
#      inst: [fadd.s, fsub.s, fmul.s, fdiv.s, fsqrt.s] 
#      dest: 0,31
#      reg1: 0,31
#      reg2: 0,31
#      rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
#      # Needs to be above 46464
#      tests_per_instruction: 46464
#      num_tests: 5
set_1:
      inst: [fadd.d] 
      dest: 0,31
      reg1: 0,31
      reg2: 0,31
      rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
      # Needs to be above 46464
      tests_per_instruction: 46464
      num_tests: 1

# set_2:
#      inst: [fadd.s, fmul.s] 
#      dest: 0,31
#      reg1: 0,31
#      reg2: 0,31
#      rounding-mode: [RNE, RTZ, RDN]
#      # Needs to be above 46464
#      tests_per_instruction: 50000
#      num_tests: 1 

#set_3:
#    inst: [fcvt.w.s, fcvt.l.s]
#    dest: 5,9
#    reg1: 5,12
#    reg2: 5,10
#    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
#    tests_per_instruction: 50000
#    num_tests: 1

#set_4:
#    inst: [feq.s]
#    dest: 5,9
#    reg1: 0,12
#    reg2: 0,10
#    rounding-mode: [RNE, RTZ, RDN, RUP, RMM]
#    tests_per_instruction: 50000
#    num_tests: 1

      #set_5:
      #     inst: [fmadd.s]
      #     dest: 0,9
      #     reg1: 0,12
      #     reg2: 0,10
      #     reg3: 0,10
      #     rounding-mode: [RNE]
      #     tests_per_instruction: 6133248
      #     num_tests: 1
