objdump:
  command: riscv64-unknown-elf-objdump
  args: -D 
elf2hex:
  command: elf2hex
  args: [8, 4194304, 2147483648]
  out_file: code.mem
sim:
  command: chromite_core
  path: /home/vagrant/core/chromite/bin/
  args: +rtldump
